# Generated by Django 4.2.3 on 2023-12-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_hidden_password_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hidden_password',
        ),
    ]
